elasticsearch.username: elastic
elasticsearch.password: password
elasticsearch.hosts: http://elasticsearch:9200/
server.host: "0.0.0.0"
server.name: kibana
elasticsearch.requestTimeout: 90000
#i18n.locale: zh-CN #中文
